### ISSUE TITLE
Detect non-responsiveness (ANR) in Electron applications

### ISSUE THREAD

**Issue by cstavitsky** [getsentry/sentry-electron#729]
### Problem Statement

Submitting on behalf of a customer:

> We have received feedback from our users regarding instances of unresponsiveness in our application. As such, we are keen on leveraging the capabilities of Sentry’s Electron SDK to implement ANR detection. 

The Electron SDK currently does not detect non-responsiveness/ANRs. 

#### Prior work: 

- Android ANR: https://docs.sentry.io/platforms/android/configuration/app-not-respond/
- Unity ANR: https://docs.sentry.io/platforms/unity/configuration/app-not-responding/
- App Hangs for iOS: https://docs.sentry.io/platforms/apple/configuration/app-hangs/

### Solution Brainstorm

> We are interested in understanding whether the SDK offers built-in capabilities to detect and handle application unresponsiveness.

An internal chat with Abhi on slack notes that we may be able to do watchdog approach that monitors the main thread but it’ll have to investigated more.
```[tasklist]
### Tasks
- [x] https://github.com/getsentry/sentry-javascript/pull/9079
- [x] https://github.com/getsentry/sentry-javascript/pull/9128
- [ ] https://github.com/getsentry/sentry-electron/pull/753
- [ ] https://github.com/getsentry/sentry-electron/pull/762
- [ ] https://github.com/getsentry/sentry-docs/pull/8146
- [ ] #770
- [ ] https://github.com/getsentry/sentry-javascript/pull/9268
```

**Comment by AbhiPrasad** [comment]
@timfish could we do a quick investigation into how much time/effort this will take?

**Comment by timfish** [comment]
Electron has the [`unresponsive` event](https://www.electronjs.org/docs/latest/api/web-contents#event-unresponsive ) for renderer processes.

By default [we currently only log breadcrumbs](https://github.com/getsentry/sentry-electron/blob/24bbeef183e2c1edda7248c21b1956d3727e819c/src/main/integrations/electron-breadcrumbs.ts#L69) for these events.

**Comment by fredyangRC** [comment]
As we briefly discussed in the meeting with your CFO and Anthony, ANR (or app freeze) monitoring is as critical as crash monitoring. I see on your web site that other platforms (mobile, Mac) actually are supported but the Windows. This is an essential function we are looking for. 
We missed a major freeze issue in the recent release that caused a lot of customer complaints, and the analysis and troubleshooting was super hard due to lacking of this monitoring ability.

If Sentry cannot support it, then we have to develop this solution in house and that somewhat de-values the Sentry.

**Comment by AbhiPrasad** [comment]
We're gonna take a more active look at this, but we need to spend time to make sure the solution has low overhead and is compatible with multiple Node/Electron versions. https://github.com/getsentry/sentry-javascript/discussions/9027

our end goal is not just to detect an ANR, but give you a stacktrace of what is causing it - hence the extra effort involved here.

Appreciate your patience while we investigate and experiment.

**Comment by timfish** [comment]
The top post now has a task list covering all the PRs adding ANR support to Electron

**Comment by AbhiPrasad** [comment]
Thanks to the amazing work of @timfish we've shipped initial ANR tracking support for Electron in a beta state in [`4.13.0`](https://github.com/getsentry/sentry-electron/releases/tag/4.13.0). Docs are coming (being worked on here https://github.com/getsentry/sentry-docs/pull/8146).

@fredyangRC please give it a try - we would love any feedback!

**Comment by MercuryLiRC** [comment]
We will try this build and give feedback. Thank you! @AbhiPrasad @timfish

**Comment by beyondkmp** [comment]
I have a question. In this https://github.com/getsentry/sentry-electron/pull/753, there is mainProcess in options.

But From the index.d.ts in @sentry/electron 4.13.0, there's no mainProcess in options. How do I pass the options in typescript?

```typescript
/**
 * **Note** This feature is still in beta so there may be breaking changes in future releases.
 *
 * Starts a child process that detects Application Not Responding (ANR) errors.
 *
 * It's important to await on the returned promise before your app code to ensure this code does not run in the ANR
 * child process.
 *
 * ```js
 * import { init, enableAnrDetection } from '@sentry/electron';
 *
 * init({ dsn: "__DSN__" });
 *
 * // with ESM + Electron v28+
 * await enableAnrDetection({ captureStackTrace: true });
 * runApp();
 *
 * // with CJS
 * enableAnrDetection({ captureStackTrace: true }).then(() => {
 *   runApp();
 * });
 * ```
 */
export declare function enableAnrDetection(options: Parameters<typeof enableNodeAnrDetection>[0]): Promise<void>;
//# sourceMappingURL=index.d.ts.map
```

**Comment by beyondkmp** [comment]
Currently, ANRs can only be detected if they are caused by JavaScript code within the main process. If I directly suspend the main process from within the Process Explorer tool, this situation cannot be monitored. Is this the expected behavior?

![image](https://github.com/getsentry/sentry-electron/assets/5462444/6ecf3725-2844-46b5-b2f0-7992bf6d2896)

**Comment by timfish** [comment]
> there's no mainProcess in options

`mainProcess` is in the typescript types. It looks like the jsdocs are incorrect and need updating.

> Currently, ANRs can only be detected if they are caused by JavaScript code

ANR will be detected whenever the main process JavaScript event loop is prevented from running and sending messages to the ANR process.

**Comment by beyondkmp** [comment]
In my code, I cannot use mainProcess. There's an error. 
![image](https://github.com/getsentry/sentry-electron/assets/5462444/439b0533-be37-48a9-958f-864c34a1e828)

**Comment by timfish** [comment]
Ah you're correct, the types exported from `@sentry/electron` are not correct. I will fix these in a PR. 

Until then, the types exported from `@sentry/electron/main` are correct.

**Comment by MercuryLiRC** [comment]
Hi @timfish 
Will Sentry provide a dashboard to monitor the ANR rate? Currently, we are unable to monitor the ANR rate in the dashboard and have to calculate it manually.

**Comment by timfish** [comment]
> Will Sentry provide a dashboard to monitor the ANR rate?

I will find out what's required to get that working.

Do you have any feedback to share? For example are ANR levels what you would expect? Do you have `captureStackTrace` enabled and if so are the stack traces useful?

**Comment by AbhiPrasad** [comment]
As per https://github.com/getsentry/develop/pull/931 we can add the `abnormal_mechanism` mechanism field to sessions to indicate to Sentry if a session was errored because of ANR.

ref https://github.com/getsentry/sentry-java/pull/2475 and cc @romtsn

Abnormal mechanism can be either one of `anr_foreground` or `anr_background as per https://github.com/getsentry/sentry/blob/bf6651cb323c6c45eab2b31d4078b21756dbdff6/src/sentry/sentry_metrics/indexer/strings.py#L139-L140

**Comment by AbhiPrasad** [comment]
Opened https://github.com/getsentry/sentry-electron/issues/774 to track ANR rate separately @MercuryLiRC please follow GH issue there for progress on that!

**Comment by timfish** [comment]
It's worth noting that in the next release, `enableAnrDetection` has been renamed to `enableMainProcessAnrDetection` so it's clear that this method is only for enabling main process ANR detection. 

```ts
/**
 * **Note** This feature is still in beta so there may be breaking changes in future releases.
 *
 * Starts a child process that detects Application Not Responding (ANR) errors.
 *
 * It's important to await on the returned promise before your app code to ensure this code does not run in the ANR
 * child process.
 *
 * ```js
 * import { init, enableMainProcessAnrDetection } from '@sentry/electron';
 *
 * init({ dsn: "__DSN__" });
 *
 * // with ESM + Electron v28+
 * await enableMainProcessAnrDetection({ captureStackTrace: true });
 * runApp();
 *
 * // with CJS
 * enableMainProcessAnrDetection({ captureStackTrace: true }).then(() => {
 *   runApp();
 * });
 * ```
 */
export function enableMainProcessAnrDetection(options: Parameters<typeof enableNodeAnrDetection>[0]): Promise<void> {
```
